Adds CI test to run pipeline job on CloudOS (#2)
* Adds cloudos_test

* Fixes which config to use

* Outsources cloudos workspace id as github secret

* Changes ci github clone command to use token for authentication

* Fix typo

* Adds step to install requests deps to CI test

* Fixes ci test config path with $GITHUB_WORKSPACE

* dbugging

* debugging

* debug

* Adds missing cloudos_test.config to config folder

* Removes debugging options

* Adds errorStrategy to repeat 5 times and fail

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -47,3 +47,45 @@ jobs:
       - name: Run pipeline with test data
         run: |
           nextflow run ${GITHUB_WORKSPACE} --config conf/test.config
+
+  test_cloudos:
+    name: Run workflow tests on CloudOS
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: [3.7]
+    steps:
+      - uses: actions/checkout@v2
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install requests
+          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+      - name: Submit job with cloudos.py 
+        env:
+          CLOUDOS_TOKEN: ${{ secrets.CLOUDOS_TOKEN }}
+          CLOUDOS_WORKSPACE: ${{ secrets.CLOUDOS_WORKSPACE }}
+          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
+        run: |
+          git clone https://${TOKEN_GITHUB}:x-oauth-basic@github.com/lifebit-ai/cloudos-cli.git
+          response=$(./cloudos-cli/cloudos.py -a $CLOUDOS_TOKEN -t $CLOUDOS_WORKSPACE -w 'lifebit-ai-hic' --config ${GITHUB_WORKSPACE}/conf/cloudos_test.config --project_name "CI tests" --job_name "cloudos-cli test")
+          echo $response
+          id=$(echo $response | cut -f6 -d / -)
+
+          JOB_STATUS='initializing'
+          while [ $JOB_STATUS = "initializing" ] || [ $JOB_STATUS = "running" ]; do
+            sleep 5
+            JOB_STATUS=$(./cloudos-cli/get_job_status.py -a $CLOUDOS_TOKEN -j $id)
+          done
+          
+          if [ $JOB_STATUS = "completed" ]; then
+            echo "SUCCESS! Job successfully completed on CloudOS!"
+          else
+            echo "Job status: $JOB_STATUS"
+            echo "ERROR: job $id failed on CLoudOS. Check the job at https://cloudos.lifebit.ai/app/jobs/${id}"
+            exit 123
+          fi
